#!/bin/sh
HOST=$(hostname)
for i in $(seq 20); do
  key=$(perl -e 'srand; printf int(rand(100000000000000000))')
  su -c "xauth add ${HOST}/unix:${i} . ${key}${key}" docker
done

su -c "cd /home/docker/jondofox_linux_bsd && ./install_jondofox.sh" docker

DISPLAY=:10 su -c "iceweasel" docker

rm -f /etc/ssh/ssh_host_dsa_key
ssh-keygen -t dsa -N '' -f /etc/ssh/ssh_host_dsa_key
rm -f /etc/ssh/ssh_host_rsa_key
ssh-keygen -t rsa -N '' -f /etc/ssh/ssh_host_rsa_key
rm -f /etc/ssh/ssh_host_ecdsa_key
ssh-keygen -t ecdsa -N '' -f /etc/ssh/ssh_host_ecdsa_key
rm -f /etc/ssh/ssh_host_ed25519_key
ssh-keygen -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key

/usr/sbin/sshd -D -f /etc/ssh/sshd_config -E /dev/stderr
